--- #YAML:1.0
name:               Config-Generator
version:            0.7
abstract:           general purpose configuration generator
author:
    - Lionel Cons <lionel.cons@cern.ch>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Config::General:    0
    Config::Validator:  1.2
    Digest::MD5:        0
    FindBin:            0
    Getopt::Long:       0
    JSON:               0
    No::Worries:        1.1
    Params::Validate:   0
    Pod::Usage:         0
    POSIX:              0
    Test::More:         0
    XML::Parser:        0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.55_02
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
